# Generated by Django 5.2.7 on 2026-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unique key for admin / future detail URLs.', unique=True)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list, help_text='List of strings, e.g. ["React", "Django"]. Matches frontend `tech` array.')),
                ('status', models.CharField(default='Live', max_length=64)),
                ('link', models.URLField(blank=True, default='', help_text='Project URL (use # if none).')),
                ('color', models.CharField(default='var(--color-accent)', help_text='CSS color token or hex, e.g. var(--color-accent) or #d4a843', max_length=120)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
    ]
